version: "3"
services:
  imagor:
    image: shumc/imagor:latest
    environment:
      PORT: 8000
      IMAGOR_SECRET: mysecret
      AWS_ACCESS_KEY_ID: AKIA4MTWJKRPI5EVQSXU
      AWS_SECRET_ACCESS_KEY: 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
      AWS_REGION: ap-south-1

      S3_LOADER_BUCKET: lambda-test-aman-demo # enable S3 loader by specifying bucket
      S3_LOADER_BASE_DIR: images # optional

      S3_STORAGE_BUCKET: lambda-test-aman-demo # enable S3 storage by specifying bucket
      # S3_STORAGE_BASE_DIR: images # optional
      # S3_STORAGE_ACL: public-read # optional - see https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#canned-acl

      S3_RESULT_STORAGE_BUCKET: lambda-test-aman-demo # enable S3 result storage by specifying bucket
      # S3_RESULT_STORAGE_BASE_DIR: images/result # optional
      # S3_RESULT_STORAGE_ACL: public-read # optional
    ports:
      - "8000:8000"